version: '3.3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/rust
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    # network_mode: "host"
    environment:
      - TZ=Asia/Tokyo
    env_file: devcontainer.env
